# Global prompt format configuration
format = """
[î‚¶](#3B4252)\
$python\
$username\
[î‚°](bg:#434C5E fg:#3B4252)\
$directory\
[î‚°](fg:#434C5E bg:#4C566A)\
$git_branch\
$git_status\
[î‚°](fg:#4C566A bg:#86BBD8)\
$c\
$elixir\
$elm\
$golang\
$haskell\
$java\
$julia\
$nodejs\
$nim\
$rust\
[î‚°](fg:#86BBD8 bg:#06969A)\
$docker_context\
[î‚°](fg:#06969A bg:#33658A)\
$time\
[î‚´ ](fg:#33658A)\
"""

command_timeout = 5000

# Disable the blank line at the start of the prompt
# add_newline = false

# Username configuration
[username]
show_always = true
style_user = "bg:#3B4252"
style_root = "bg:#3B4252"
format = '[$user ]($style)'

# Directory configuration
[directory]
style = "bg:#434C5E"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "â€¦/"
home_symbol = "ğŸ " # This sets the symbol for the home directory

# Directory path substitutions (shortening)
[directory.substitutions]
"Documents" = " ó°ˆ™ "
"Downloads" = " ï€™ "
"Music" = " ï€ "
"Pictures" = " ï€¾ "
"Applications" = " ó°€» "
"Desktop" = " ó°Ÿ€ "
"Movies" = " ï€ˆ "
"Google Drive" = " î‰† "
"Contacts" = " ó°›‹ "
"Favorites" = " ó°š "
"Users" = " ï€‡ "
"Videos" = " ï€ˆ "
".config" = " î˜• "
".ssh" = " ó°£€ "

# C module configuration
[c]
symbol = "î˜ "
style = "bg:#86BBD8"
format = '[ $symbol ($version) ]($style)'

# Docker context configuration
[docker_context]
symbol = "ïŒˆ "
style = "bg:#06969A"
format = '[ $symbol ]($style)'

# Elixir configuration
[elixir]
symbol = "î‰µ "
style = "bg:#86BBD8"
format = '[ $symbol ($version) ]($style)'

# Elm configuration
[elm]
symbol = "î˜¬ "
style = "bg:#86BBD8"
format = '[ $symbol ($version) ]($style)'

# Golang configuration
[golang]
symbol = "î˜§ "
style = "bg:#86BBD8"
format = '[ $symbol ($version) ]($style)'

# Haskell configuration
[haskell]
symbol = "î· "
style = "bg:#86BBD8"
format = '[ $symbol ($version) ]($style)'

# Java configuration
[java]
symbol = "î‰– "
style = "bg:#86BBD8"
format = '[ $symbol ($version) ]($style)'

# Julia configuration
[julia]
symbol = "î˜¤ "
style = "bg:#86BBD8"
format = '[ $symbol ($version) ]($style)'

# Node.js configuration
[nodejs]
symbol = "îœ˜"
style = "bg:#86BBD8"
format = '[ $symbol ($version) ]($style)'

# Nim configuration
[nim]
symbol = "ïš¤ "
style = "bg:#86BBD8"
format = '[ $symbol ($version) ]($style)'

# Python configuration
[python]
style = "bg:#3B4252"
format = '[(\($virtualenv\) )]($style)'

# Rust configuration
[rust]
symbol = "î¨"
style = "bg:#86BBD8"
format = '[ $symbol ($version) ]($style)'

# Git branch configuration (disabled)
[git_branch]
symbol = "ï„“"
style = "bg:#4C566A"
format = '[ $symbol $branch ]($style)'
disabled = true

# Git status configuration (disabled)
[git_status]
style = "bg:#4C566A"
format = '[$all_status$ahead_behind ]($style)'
disabled = true

# Time configuration
[time]
disabled = false
time_format = "%R" # Hour:Minute Format
style = "bg:#33658A"
format = '[ $time ]($style)'